name: flutter_ast
description: A Pure Dart File to Ast Serializer/Deserializer.
version: 0.0.4
homepage: https://github.com/gridaco/flutter-support/tree/main/flutter_ast/
license: MIT

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_cli_annotations: ^2.1.0
  analyzer: ^5.4.0
  path: ^1.8.3
  console: ^4.1.0
  mustache_template: ^2.0.0
  _fe_analyzer_shared: ^52.0.0
  recase: ^4.1.0
  flutter_ast_core: ^0.0.4
  # flutter_ast_core:
  #   path: ../flutter_ast_core

dev_dependencies:
  build_runner: ^2.3.3
  build_cli: ^2.2.1
  node_preamble: ^2.0.1
  grinder: ^0.9.2
  test: any
