name: flutter_ast_core
description: Flutter AST Parser Core models for flutter_ast
version: 0.0.1
homepage: https://github.com/gridaco/flutter-support/tree/main/flutter_ast/flutter_ast_core
license: MIT

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: any
  freezed: ^2.3.2
  json_serializable: ^6.6.0

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
